/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learnopengl;

public class App {

    String greeting = "Hello Brotheren";

    public String getGreeting() {
        return greeting;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
