/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learnopengl;

import learnopengl.chapter1.HelloWindow;
import learnopengl.chapter2.HelloTriangle;
import learnopengl.chapter3.Shaders;
import learnopengl.chapter4.Textures;
import learnopengl.chapter5.Transformations;
import learnopengl.chapter6.CoordinateSystems;

import java.util.List;
import java.util.Objects;
import java.util.Scanner;

public class App {

    public static String CHAPTER_1 = "chapter1";

    public static List<String> chapters = List.of(
            CHAPTER_1
    );

    public static void main(String[] args) {

        Runner runner =  null;
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter your enter a chapter: ");
        String chapter = "";
        chapter = scanner.nextLine();


        switch (chapter) {

            case "chapter1":
                runner = new HelloWindow();
                break;
            case "chapter2":
                runner = new HelloTriangle();
                break;
            case "chapter3":
                runner = new Shaders();
                break;
            case "chapter4":
                runner = new Textures();
                break;
            case "chapter5":
                runner = new Transformations();
                break;
            case "chapter6":
                runner = new CoordinateSystems();
                break;
            default:
                String demos = String.join("\n", chapters);
                System.out.printf("Rerun the program and choose one of the following demos:\n %s%n", demos);
                break;
        }

        if(Objects.nonNull(runner))
            runner.run();
    }
}
